# See https://pre-commit.com for more information
repos:
  # Python formatters
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        files: ^backend/.*\.py$

  # Python linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/.*\.py$

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black]
        files: ^backend/.*\.py$

  # JavaScript/TypeScript/Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, html, css]
        exclude: ^(backend/|\.gitignore|\.dockerignore)

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(.github/workflows/|infra/ci/)
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
        files: ^backend/.*\.py$
      - id: mixed-line-ending
        args: [--fix=lf]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package-lock\.json

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]
        files: \.md$
        exclude: ^(node_modules/|.venv/)

# Configuration
default_language_version:
  python: python3.11

# Run configuration
fail_fast: false
exclude: |
  (?x)^(
    node_modules/|
    venv/|
    .venv/|
    build/|
    dist/|
    .*\.egg-info/|
    htmlcov/|
    \.git/|
    \.pytest_cache/|
    \.mypy_cache/|
    \.ruff_cache/|
    __pycache__/|
    migrations/|
    static/|
    media/
  )