"""
Step-by-step guide to get a fresh eBay OAuth token.
"""
print("Your eBay OAuth token has EXPIRED.")
print("eBay tokens only last ~2 hours, so this is normal.")
print()
print("To get a fresh token, you need to:")
print()
print("1. Go to: https://developer.ebay.com/my/keys")
print("2. Sign in to your eBay Developer account")
print("3. Find your Application (not 'User Token')")
print("4. Look for these two values:")
print("   - App ID (Client ID)")
print("   - Client Secret (Cert ID)")
print()
print("5. Run this command with YOUR credentials:")
print()
print("python -c \"")
print("import requests, base64")
print("client_id = 'YOUR_APP_ID_HERE'")
print("client_secret = 'YOUR_CLIENT_SECRET_HERE'")
print("creds = base64.b64encode(f'{client_id}:{client_secret}'.encode()).decode()")
print("resp = requests.post('https://api.ebay.com/identity/v1/oauth2/token',")
print("                     headers={'Authorization': f'Basic {creds}',")
print("                              'Content-Type': 'application/x-www-form-urlencoded'},")
print("                     data={'grant_type': 'client_credentials',")
print("                           'scope': 'https://api.ebay.com/oauth/api_scope/buy.item.browse'})")
print("if resp.status_code == 200:")
print("    token = resp.json()['access_token']")
print("    print(f'SUCCESS: {token}')")
print("    print('Set this as EBAY_OAUTH_TOKEN in your .env file')")
print("else:")
print("    print(f'ERROR {resp.status_code}: {resp.text}')")
print("\"")
print()
print("6. Copy the new token and update your .env file")
print("7. Test again with the fresh token")
print()
print("The token will be valid for ~2 hours.")
