[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# These will be set in Railway dashboard
# EBAY_VERIFICATION_TOKEN = "will be set in dashboard"
# KEEPA_API_KEY = "will be set in dashboard"
# EBAY_SANDBOX_TOKEN = "will be set in dashboard"
